
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    template-loader-path: /templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

#mybatis配置
mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
#日志配置
logging:
  config: classpath:logback.xml
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

